<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Zend Framework Tutorial');
echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?>
    <link rel="stylesheet" type="text/css" href="http://localhost:8080/CrudTest/library/DataTables/media/css/jquery.dataTables.css">
    <script type="text/javascript" language="javascript" src="http://localhost:8080/CrudTest/library/DataTables/media/js/jquery.js"></script>
    <script type="text/javascript" language="javascript" src="http://localhost:8080/CrudTest/library/DataTables/media/js/jquery.dataTables.min.js"></script>

    <script>
        $(function(){
            $("#demo").dataTable();
        });
    </script>

</head>
<body>
<div id="content" class="display">
    <h1><?php echo $this->escape($this->title); ?></h1>
    <?php echo $this->layout()->content; ?>
</div>
</body>
</html>